## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './data/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [27]:
print ("Row number is: {}".format(app_train.shape[0]))
print ("Columne number is: {}".format(app_train.shape[1]))

Row number is: 307511
Columne number is: 122

#### 列出所有欄位

In [50]:
print (app_train.columns.tolist())

['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR']

#### 截取部分資料

In [45]:
app_train[['CODE_GENDER', 'NAME_CONTRACT_TYPE']]

       CODE_GENDER NAME_CONTRACT_TYPE
0                M         Cash loans
1                F         Cash loans
2                M    Revolving loans
3                F         Cash loans
4                M         Cash loans
5                M         Cash loans
6                F         Cash loans
7                M         Cash loans
8                F         Cash loans
9                M    Revolving loans
10               F         Cash loans
11               F         Cash loans
12               F         Cash loans
13               M         Cash loans
14               F         Cash loans
15               M         Cash loans
16               M         Cash loans
17               F    Revolving loans
18               F    Revolving loans
19               F         Cash loans
20               M    Revolving loans
21               F         Cash loans
22               F         Cash loans
23               F         Cash loans
24               M         Cash loans
25               F         Cash loans
26               F         Cash loans
27               M         Cash loans
28               M         Cash loans
29               M    Revolving loans
...            ...                ...
307481           M         Cash loans
307482           F         Cash loans
307483           F         Cash loans
307484           F         Cash loans
307485           F    Revolving loans
307486           F         Cash loans
307487           M         Cash loans
307488           F         Cash loans
307489           F         Cash loans
307490           M         Cash loans
307491           M         Cash loans
307492           M         Cash loans
307493           F         Cash loans
307494           M         Cash loans
307495           M         Cash loans
307496           F    Revolving loans
307497           F         Cash loans
307498           M         Cash loans
307499           F         Cash loans
307500           F         Cash loans
307501           F         Cash loans
307502           F         Cash loans
307503           F         Cash loans
307504           F         Cash loans
307505           F         Cash loans
307506           M         Cash loans
307507           F         Cash loans
307508           F         Cash loans
307509           F         Cash loans
307510           F         Cash loans

[307511 rows x 2 columns]

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子

Filter out non-revolving loans data

In [55]:
is_Revolving = app_train['NAME_CONTRACT_TYPE'] == "Revolving loans"
print (app_train[is_Revolving])

        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
2           100004       0    Revolving loans           M            Y
9           100012       0    Revolving loans           M            N
17          100021       0    Revolving loans           F            N
18          100022       0    Revolving loans           F            N
20          100024       0    Revolving loans           M            Y
29          100034       0    Revolving loans           M            N
39          100046       0    Revolving loans           M            Y
45          100052       0    Revolving loans           F            N
50          100058       0    Revolving loans           F            N
57          100068       0    Revolving loans           M            N
67          100079       0    Revolving loans           M            N
68          100080       0    Revolving loans           F            N
76          100088       0    Revolving loans           F            N
80          100095       0    Revolving loans           F            N
83          100098       0    Revolving loans           M            Y
100         100119       0    Revolving loans           F            N
107         100126       0    Revolving loans           M            N
109         100129       0    Revolving loans           F            Y
114         100134       0    Revolving loans           F            N
120         100140       0    Revolving loans           F            N
122         100143       0    Revolving loans           M            N
132         100154       0    Revolving loans           M            N
147         100174       0    Revolving loans           F            N
155         100182       0    Revolving loans           F            N
165         100194       0    Revolving loans           F            N
180         100209       1    Revolving loans           M            N
194         100226       0    Revolving loans           F            N
198         100230       0    Revolving loans           F            N
201         100234       0    Revolving loans           F            N
233         100270       0    Revolving loans           F            N
...            ...     ...                ...         ...          ...
307129      455825       0    Revolving loans           F            N
307133      455830       1    Revolving loans           F            N
307137      455834       0    Revolving loans           F            N
307184      455887       0    Revolving loans           M            N
307188      455891       0    Revolving loans           F            N
307199      455904       0    Revolving loans           M            Y
307209      455917       0    Revolving loans           F            N
307210      455918       0    Revolving loans           F            N
307220      455928       0    Revolving loans           M            Y
307226      455934       0    Revolving loans           F            Y
307234      455943       0    Revolving loans           F            Y
307235      455944       0    Revolving loans           F            N
307286      456003       0    Revolving loans           F            Y
307287      456004       0    Revolving loans           F            Y
307298      456021       0    Revolving loans           F            N
307302      456025       0    Revolving loans           F            N
307314      456038       0    Revolving loans           F            N
307332      456056       0    Revolving loans           M            N
307372      456097       0    Revolving loans           M            N
307375      456100       0    Revolving loans           F            N
307384      456109       0    Revolving loans           M            N
307385      456110       0    Revolving loans           M            Y
307402      456135       0    Revolving loans           F            N
307419      456152       0    Revolving loans           F            N
307425      456158       0    Revolving loans           M            Y
307444      456182       0    Revolving loans           F            N
307457      456196       0    Revolving loans           F            N
307467      456207       0    Revolving loans           F            N
307485      456229       0    Revolving loans           F            N
307496      456240       0    Revolving loans           F            N

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
2                    Y             0           67500.0    135000.0
9                    Y             0          135000.0    405000.0
17                   Y             1           81000.0    270000.0
18                   Y             0          112500.0    157500.0
20                   Y             0          135000.0    427500.0
29                   Y             0           90000.0    180000.0
39                   Y             0          180000.0    540000.0
45                   Y             1           90000.0    180000.0
50                   Y             0           54000.0    135000.0
57                   Y             0           81000.0    247500.0
67                   Y             0          225000.0    270000.0
68                   N             1          157500.0    450000.0
76                   N             0          112500.0    135000.0
80                   Y             2           67500.0    135000.0
83                   N             0          225000.0    270000.0
100                  Y             0           54000.0    180000.0
107                  Y             2          135000.0    180000.0
109                  Y             1           85500.0    135000.0
114                  N             0          202500.0    180000.0
120                  N             0          157500.0    675000.0
122                  Y             0          162000.0    270000.0
132                  N             0          144000.0    180000.0
147                  Y             2          180000.0    225000.0
155                  Y             1          112500.0    135000.0
165                  Y             2          157500.0    315000.0
180                  Y             3          180000.0    540000.0
194                  N             2          112500.0    270000.0
198                  N             0          135000.0    405000.0
201                  N             0           67500.0    180000.0
233                  Y             0           90000.0    337500.0
...                ...           ...               ...         ...
307129               Y             0          360000.0    765000.0
307133               Y             0           90000.0    135000.0
307137               Y             0          139500.0    180000.0
307184               Y             0          157500.0    202500.0
307188               Y             0          180000.0    382500.0
307199               Y             2          202500.0    270000.0
307209               Y             0          180000.0    270000.0
307210               Y             0           72000.0    157500.0
307220               Y             0          135000.0    270000.0
307226               Y             0          166500.0    225000.0
307234               N             0           72000.0    180000.0
307235               Y             0           63000.0    180000.0
307286               Y             2           90000.0    180000.0
307287               Y             0          135000.0    405000.0
307298               Y             0          180000.0    405000.0
307302               Y             0          144000.0    180000.0
307314               N             1          121500.0    382500.0
307332               Y             1          193500.0    180000.0
307372               Y             0          112500.0    180000.0
307375               Y             0           63000.0    135000.0
307384               N             0          180000.0    270000.0
307385               Y             2          180000.0    180000.0
307402               Y             0          157500.0    382500.0
307419               N             1          112500.0    450000.0
307425               Y             2          234000.0    450000.0
307444               Y             2           90000.0    270000.0
307457               Y             2          202500.0    360000.0
307467               Y             0          247500.0    675000.0
307485               Y             1          270000.0    180000.0
307496               N             0          360000.0    337500.0

        AMT_ANNUITY  ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20  \
2            6750.0  ...                 0                0                0
9           20250.0  ...                 0                0                0
17          13500.0  ...                 0                0                0
18           7875.0  ...                 0                0                0
20          21375.0  ...                 0                0                0
29           9000.0  ...                 0                0                0
39          27000.0  ...                 0                0                0
45           9000.0  ...                 0                0                0
50           6750.0  ...                 1                0                0
57          12375.0  ...                 0                0                0
67          13500.0  ...                 0                0                0
68          22500.0  ...                 0                0                0
76           6750.0  ...                 0                0                0
80           6750.0  ...                 0                0                0
83          13500.0  ...                 0                0                0
100          9000.0  ...                 0                0                0
107          9000.0  ...                 0                0                0
109          6750.0  ...                 0                0                0
114          9000.0  ...                 0                0                0
120         33750.0  ...                 0                0                0
122         13500.0  ...                 0                0                0
132          9000.0  ...                 0                0                0
147         11250.0  ...                 0                0                0
155          6750.0  ...                 0                0                0
165         15750.0  ...                 0                0                0
180         27000.0  ...                 0                0                0
194         13500.0  ...                 0                0                0
198         20250.0  ...                 0                0                0
201          9000.0  ...                 0                0                0
233         16875.0  ...                 0                0                0
...             ...  ...               ...              ...              ...
307129      38250.0  ...                 0                0                0
307133       6750.0  ...                 0                0                0
307137       9000.0  ...                 0                0                0
307184      10125.0  ...                 0                0                0
307188      19125.0  ...                 0                0                0
307199      13500.0  ...                 0                0                0
307209      13500.0  ...                 0                0                0
307210       7875.0  ...                 0                0                0
307220      13500.0  ...                 0                0                0
307226      11250.0  ...                 0                0                0
307234       9000.0  ...                 0                0                0
307235       9000.0  ...                 0                0                0
307286       9000.0  ...                 0                0                0
307287      20250.0  ...                 0                0                0
307298      20250.0  ...                 0                0                0
307302       9000.0  ...                 0                0                0
307314      19125.0  ...                 0                0                0
307332       9000.0  ...                 0                0                0
307372       9000.0  ...                 0                0                0
307375       6750.0  ...                 0                0                0
307384      13500.0  ...                 0                0                0
307385       9000.0  ...                 0                0                0
307402      19125.0  ...                 0                0                0
307419      22500.0  ...                 0                0                0
307425      22500.0  ...                 0                0                0
307444      13500.0  ...                 0                0                0
307457      18000.0  ...                 0                0                0
307467      33750.0  ...                 0                0                0
307485       9000.0  ...                 0                0                0
307496      16875.0  ...                 0                0                0

       FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
2                     0                        0.0                       0.0
9                     0                        NaN                       NaN
17                    0                        NaN                       NaN
18                    0                        0.0                       0.0
20                    0                        NaN                       NaN
29                    0                        NaN                       NaN
39                    0                        0.0                       0.0
45                    0                        NaN                       NaN
50                    0                        0.0                       0.0
57                    0                        0.0                       0.0
67                    0                        0.0                       0.0
68                    0                        0.0                       0.0
76                    0                        0.0                       0.0
80                    0                        NaN                       NaN
83                    0                        NaN                       NaN
100                   0                        0.0                       0.0
107                   0                        0.0                       0.0
109                   0                        1.0                       0.0
114                   0                        0.0                       0.0
120                   0                        NaN                       NaN
122                   0                        0.0                       0.0
132                   0                        0.0                       0.0
147                   0                        0.0                       0.0
155                   0                        0.0                       0.0
165                   0                        0.0                       0.0
180                   0                        0.0                       0.0
194                   0                        NaN                       NaN
198                   0                        0.0                       0.0
201                   0                        0.0                       0.0
233                   0                        0.0                       0.0
...                 ...                        ...                       ...
307129                0                        NaN                       NaN
307133                0                        0.0                       0.0
307137                0                        0.0                       0.0
307184                0                        0.0                       0.0
307188                0                        0.0                       0.0
307199                0                        0.0                       0.0
307209                0                        0.0                       0.0
307210                0                        0.0                       0.0
307220                0                        0.0                       0.0
307226                0                        0.0                       0.0
307234                0                        0.0                       0.0
307235                0                        0.0                       0.0
307286                0                        0.0                       0.0
307287                0                        0.0                       0.0
307298                0                        0.0                       0.0
307302                0                        0.0                       1.0
307314                0                        0.0                       0.0
307332                0                        0.0                       0.0
307372                0                        NaN                       NaN
307375                0                        0.0                       0.0
307384                0                        0.0                       0.0
307385                0                        0.0                       0.0
307402                0                        0.0                       0.0
307419                0                        0.0                       0.0
307425                0                        0.0                       0.0
307444                0                        0.0                       0.0
307457                0                        0.0                       0.0
307467                0                        0.0                       0.0
307485                0                        0.0                       0.0
307496                0                        0.0                       0.0

        AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
2                              0.0                        0.0
9                              NaN                        NaN
17                             NaN                        NaN
18                             0.0                        0.0
20                             NaN                        NaN
29                             NaN                        NaN
39                             0.0                        1.0
45                             NaN                        NaN
50                             0.0                        0.0
57                             0.0                        0.0
67                             0.0                        1.0
68                             0.0                        0.0
76                             0.0                        0.0
80                             NaN                        NaN
83                             NaN                        NaN
100                            0.0                        0.0
107                            0.0                        0.0
109                            0.0                        0.0
114                            0.0                        0.0
120                            NaN                        NaN
122                            0.0                        0.0
132                            0.0                        0.0
147                            0.0                        0.0
155                            0.0                        0.0
165                            0.0                        0.0
180                            0.0                        0.0
194                            NaN                        NaN
198                            0.0                        0.0
201                            0.0                        0.0